# =============================================================================
#   Computeregex
#
#   @description: Makefile for computeregex.py
#   @author: ahlai
#   @version: 0.0.1 08/10/2016
# =============================================================================

all:
		@echo "Granting file execution permissions..."
		chmod +x computeregex.py

run: all
		@echo "Running..."
		./computeregex.py

clean:
		@echo "Cleaning..."
		find . -name '*.pyc' -delete
		find . -name '*.pyo' -delete
