# =============================================================================
#  Two-armed Bandit
#
#  @author: Elisha Lai
#  @description: Makefile for two_armed_bandit.py
#  @version: 0.0.1 30/10/2016
# =============================================================================

all:
	@echo "Granting file execution permissions..."
	chmod +x two_armed_bandit.py

run: all
	@echo "Running..."
	./two_armed_bandit.py

.PHONY: clean

clean:
	@echo "Cleaning..."
	find . -name "*.pyc" -delete
	find . -name "*.pyo" -delete
	find . -name "__pycache__" -delete
