# =============================================================================
#   Computeregex
#
#   @description: Makefile for computeregex.py
#   @author: ahlai
# =============================================================================

all:
		@echo "Granting file execution permissions..."
		chmod +x reg

run: all
		@echo "Running..."
		./reg
